sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.1.3
loading pickled environment... done
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 4 changed, 0 removed
reading sources... [ 25%] generated/sadit.Configure
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
ImportError: No module named TestMSGenerator
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
ImportError: No module named TestMultiServer
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
ImportError: No module named TestNetwork
reading sources... [ 50%] generated/sadit.Detector
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
reading sources... [ 75%] generated/sadit.Experiment
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Experiment/Detect.py", line 7, in <module>
    from Detector import detect
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Experiment/DetectBatch.py", line 7, in <module>
    from Detect import Detect
  File "/home/wangjing/Dropbox/Research/sadit/Experiment/Detect.py", line 7, in <module>
    from Detector import detect
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Experiment/DetectCompare.py", line 6, in <module>
    from Detect import Detect
  File "/home/wangjing/Dropbox/Research/sadit/Experiment/Detect.py", line 7, in <module>
    from Detector import detect
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Experiment/Eval.py", line 6, in <module>
    from Detector.DataParser import RawParseData
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Experiment/ImalseSettings.py", line 15, in <module>
    from Detector import detect
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Experiment/MultiSrvExperiment.py", line 10, in <module>
    from Detector import detect
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Experiment/SimDetect.py", line 4, in <module>
    from Detect import Detect
  File "/home/wangjing/Dropbox/Research/sadit/Experiment/Detect.py", line 7, in <module>
    from Detector import detect
  File "/home/wangjing/Dropbox/Research/sadit/Detector/__init__.py", line 3, in <module>
    from API import detect, print_detector_help, detector_plot_dump
  File "/home/wangjing/Dropbox/Research/sadit/Detector/API.py", line 15, in <module>
    from StoDetector import *
  File "/home/wangjing/Dropbox/Research/sadit/Detector/StoDetector.py", line 779, in <module>
    from DataHandler import CombinedEM
ImportError: No module named DataHandler
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
  File "/home/wangjing/Dropbox/Research/sadit/Experiment/__test.py", line 4, in <module>
    from DetectArgSearch import *
ImportError: No module named DetectArgSearch
reading sources... [100%] run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 321, in import_object
    __import__(self.modname)
ImportError: No module named run

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 16%] generated/sadit
writing output... [ 33%] generated/sadit.Configure
writing output... [ 50%] generated/sadit.Detector
writing output... [ 66%] generated/sadit.Experiment
writing output... [ 83%] index
writing output... [100%] run

writing additional files... (49 module code pages) _modules/index
 genindex py-modindex search
copying static files... done
dumping search index... done
dumping object inventory... done
build succeeded, 1856 warnings.

Build finished. The HTML pages are in build/html.
